export default {
    class: 'Assassin',
    trees: [
        {
            name: 'Martial Arts',
            isActive: true,
            skills: [
                {
                    id: 1,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: false,
                    name: 'Tiger Strike',
                    description: 'Charge-up Skill: Through extensive training in human, animal, and demonic anatomies, Assassins have developed the ability to perceive natural points of weakness in their foes and target these locations for especially devastating attacks.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: false,
                    name: 'Dragon Talon',
                    description: 'Finishing Move: An Assassin is taught to utilize her entire body as a weapon-using this skill, she lets loose a powerful kick to send her opponents flying.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: false,
                    name: 'Fists of Fire',
                    description: 'Charge-up Skill: Combining her powerful Martial Arts abilities with her psychic training, an Assassin can charge her own fists with pyrokinetic energies, scorching her opponents when the charge is released.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: false,
                    name: 'Dragon Claw',
                    description: 'Finishing Move: This skill allows the Assassin to try to finish her opponent off with a rending double claw attack. (Requires two equipped Claw-class weapons.)',
                    points: 0,
                    prerequisites: ['Dragon Talon'],
                    unlockedBy: ['Dragon Talon'],
                    available: false,
                },
                {
                    id: 7,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 8,
                    isPlaceholder: false,
                    name: 'Cobra Strike',
                    description: 'Charge-Up Skill: A properly trained Assassin can focus her mind to draw upon the ambient energies surrounding her. Using this skill, she can drain her adversary of life and spiritual essence.',
                    points: 0,
                    prerequisites: ['Tiger Strike'],
                    unlockedBy: ['Tiger Strike'],
                    available: false,
                },
                {
                    id: 9,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 10,
                    isPlaceholder: false,
                    name: 'Claws of Thunder',
                    description: 'Charge Up Skill: Using her weapon\'s metal blades as conductors, an Assassin charges the ions surrounding her and delivers a devastating lightning attack to any who dare challenge her. (Requires equipped Claw - class weapon.)',
                    points: 0,
                    prerequisites: ['Fists of Fire'],
                    unlockedBy: ['Fists of Fire'],
                    available: false,
                },
                {
                    id: 11,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 12,
                    isPlaceholder: false,
                    name: 'Dragon Tail',
                    description: 'Finishing Move: The experienced Assassin can deliver a kick so powerful it actually causes an explosion on impact, sending any nearby victims sprawling.',
                    points: 0,
                    prerequisites: ['Dragon Talon', 'Dragon Claw'],
                    unlockedBy: ['Dragon Claw'],
                    available: false,
                },
                {
                    id: 13,
                    isPlaceholder: false,
                    name: 'Blades of Ice',
                    description: 'Charge-up Skill: Charging the ether around her claw blades, the trained Assassin can chill opponents with a vicious rake of her razors. (Requires equipped Claw-class weapon.)',
                    points: 0,
                    prerequisites: ['Fists of Fire', 'Claws of Thunder'],
                    unlockedBy: ['Claws of Thunder'],
                    available: false,
                },
                {
                    id: 14,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 15,
                    isPlaceholder: false,
                    name: 'Dragon Flight',
                    description: 'Finishing Move: After years of disciplined physical conditioning, an Assassin can develop the ability to move faster than the eye can follow in one quick burst. Using this skill, she lunges at her target and delivers a devastating kick.',
                    points: 0,
                    prerequisites: ['Dragon Talon', 'Dragon Claw', 'Dragon Tail'],
                    unlockedBy: ['Dragon Tail'],
                    available: false,
                },
                {
                    id: 16,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 17,
                    isPlaceholder: false,
                    name: 'Phoenix Strike',
                    description: 'Charge-up Skill: This mighty skill allows the Assassin trained in its arts to prepare an attack that gives off powerful elemental energies.',
                    points: 0,
                    prerequisites: ['Tiger Strike', 'Fists of Fire', 'Cobra Strike', 'Claws of Thunder', 'Blades of Ice'],
                    unlockedBy: ['Blades of Ice', 'Cobra Strike'],
                    available: false,
                },
                {
                    id: 18,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
        {
            name: 'Shadow Disciplines',
            isActive: false,
            skills: [
                {
                    id: 1,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: false,
                    name: 'Claw Mastery',
                    description: 'Passive Effect: Well-disciplined training in this skill improves the artistry with which an Assassin wields her unique Claw-class weapons.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: false,
                    name: 'Psychic Hammer',
                    description: 'Effect: By utilizing her intense mental prowess, an Assassin creates a powerful force of mental energies and directs it towards a hostile creature, blasting it backwards.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: false,
                    name: 'Burst of Speed',
                    description: 'Increases Attack And Movement Speed For A Period Of Time',
                    points: 0,
                    prerequisites: ['Claw Mastery'],
                    unlockedBy: ['Claw Mastery'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 8,
                    isPlaceholder: false,
                    name: 'Weapon Block',
                    description: 'Passive Effect: After developing this skill, an Assassin wielding two Claw-class weapons can use her blades to deflect incoming attacks, thus giving herself a defensive edge without using a shield. (Requires two equipped Claw-class weapons.)',
                    points: 0,
                    prerequisites: ['Claw Mastery'],
                    unlockedBy: ['Claw Mastery'],
                    available: false,
                },
                {
                    id: 9,
                    isPlaceholder: false,
                    name: 'Cloak of Shadows',
                    description: 'Moving through the darkness, unseen by her foes, the enshrouded Assassin can steal past opponents or ambush her unsuspecting victims with devastating attacks.',
                    points: 0,
                    prerequisites: ['Psychic Hammer'],
                    unlockedBy: ['Psychic Hammer'],
                    available: false,
                },
                {
                    id: 10,
                    isPlaceholder: false,
                    name: 'Fade',
                    description: 'An Assassin can will her physical being to shift partially into the astral planes. As her body becomes less substantial, she becomes less susceptible to the effects of elemental attacks and magical curses.',
                    points: 0,
                    prerequisites: ['Claw Mastery', 'Burst of Speed'],
                    unlockedBy: ['Burst of Speed'],
                    available: false,
                },
                {
                    id: 11,
                    isPlaceholder: false,
                    name: 'Shadow Warrior',
                    description: 'The Assassin trained in this discipline has the ability to project a "shadow" of herself. The Shadow Warrior makes use of normal attack and the two skills the Assassin has readied for herself.',
                    points: 0,
                    prerequisites: ['Claw Mastery', 'Psychic Hammer', 'Weapon Block', 'Cloak of Shadows'],
                    unlockedBy: ['Weapon Block', 'Cloak of Shadows'],
                    available: false,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 14,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 15,
                    isPlaceholder: false,
                    name: 'Mind Blast',
                    description: 'Focusing her anima, an Assassin using this potent ability can crush the will of a group of enemies, stunning them and confusing the feebleminded into attacking their comrades.',
                    points: 0,
                    prerequisites: ['Psychic Hammer', 'Cloak of Shadows'],
                    unlockedBy: ['Cloak of Shadows'],
                    available: false,
                },
                {
                    id: 16,
                    isPlaceholder: false,
                    name: 'Venom',
                    description: 'Poison use is another technique an Assassin has to help even the odds when battling demons and their ilk. An Assassin who has mastered this skill secretly coats her weapons with vile toxins.',
                    points: 0,
                    prerequisites: ['Claw Mastery', 'Burst of Speed', 'Fade'],
                    unlockedBy: ['Fade'],
                    available: false,
                },
                {
                    id: 17,
                    isPlaceholder: false,
                    name: 'Shadow Master',
                    description: 'This discipline allows an Assassin to project an even more powerful shadow avatar. The Shadow Master has access to all of the Assassin skills, also skills you don\'t have yet.',
                    points: 0,
                    prerequisites: ['Claw Mastery', 'Psychic Hammer', 'Weapon Block', 'Cloak of Shadows', 'Shadow Warrior'],
                    unlockedBy: ['Shadow Warrior'],
                    available: false,
                },
                {
                    id: 18,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
        {
            name: 'Traps',
            isActive: false,
            skills: [
                {
                    id: 1,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: false,
                    name: 'Fire Blast',
                    description: 'This skill gives an Assassin the ability to manufacture and throw a small incendiary device. This ordinance explodes on impact, damaging any foe within its small blast radius.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: false,
                    name: 'Shock Web',
                    description: 'These traps comprise a collection of small conductive components that arc electricity between one another, damaging any opponents who tread upon them.',
                    points: 0,
                    prerequisites: ['Fire Blast'],
                    unlockedBy: ['Fire Blast'],
                    available: false,
                },
                {
                    id: 5,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: false,
                    name: 'Blade Sentinal',
                    description: 'This skill allows the Assassin to throw a razor-sharp device that flies back and forth between the Assassin and its target, slicing any hostile creatures in its path.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: false,
                    name: 'Charged Bolt Sentry',
                    description: 'This small device, once cast upon the ground, emits charges of electricity that shock any adversary who strays too close.',
                    points: 0,
                    prerequisites: ['Fire Blast', 'Shock Web'],
                    unlockedBy: ['Shock Web'],
                    available: false,
                },
                {
                    id: 8,
                    isPlaceholder: false,
                    name: 'Wake of Fire',
                    description: 'Once erected, this trap releases waves of flame that incinerate any opponents within its path.',
                    points: 0,
                    prerequisites: ['Fire Blast'],
                    unlockedBy: ['Fire Blast'],
                    available: false,
                },
                {
                    id: 9,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 10,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 11,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 12,
                    isPlaceholder: false,
                    name: 'Blade Fury',
                    description: 'Using this skill, the Assassin throws several small blades, shredding her enemies with a barrage of metal.',
                    points: 0,
                    prerequisites: ['Fire Blast', 'Blade Sentinal', 'Wake of Fire'],
                    unlockedBy: ['Blade Sentinal', 'Wake of Fire'],
                    available: false,
                },
                {
                    id: 13,
                    isPlaceholder: false,
                    name: 'Lightning Sentry',
                    description: 'This device discharges great bolts of electricity, frying assailants when they come near.',
                    points: 0,
                    prerequisites: ['Fire Blast', 'Shock Web', 'Charged Bolt Sentry'],
                    unlockedBy: ['Charged Bolt Sentry'],
                    available: false,
                },
                {
                    id: 14,
                    isPlaceholder: false,
                    name: 'Wake of Inferno',
                    description: 'Enchants an arrow that does fire damage, and explodes into a patcOnce an Assassin throws it to the ground, this trap expels a large spout of fire at any opponent who moves within its range.h of fire on the ground. Creatures passing through the flames take additional damage.',
                    points: 0,
                    prerequisites: ['Fire Blast', 'Wake of Fire'],
                    unlockedBy: ['Wake of Fire'],
                    available: false,
                },
                {
                    id: 15,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 16,
                    isPlaceholder: false,
                    name: 'Death Sentry',
                    description: 'This trap emits projectiles laden with a potent chemical catalyst, detonating the exposed cadavers of slain enemies.',
                    points: 0,
                    prerequisites: ['Fire Blast', 'Shock Web', 'Charged Bolt Sentry', 'Lightning Sentry'],
                    unlockedBy: ['Lightning Sentry'],
                    available: false,
                },
                {
                    id: 17,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 18,
                    isPlaceholder: false,
                    name: 'Blade Shield',
                    description: 'This contrivance releases several small razors and uses magnetic forces to set them spinning about the Assassin, inflicting grievous wounds on any foe who approaches her too closely.',
                    points: 0,
                    prerequisites: ['Fire Blast', 'Blade Sentinal', 'Wake of Fire', 'Blade Fury'],
                    unlockedBy: ['Blade Fury'],
                    available: false,
                },
            ]
        },
    ],
}