export default {
    class: 'Barbarian',
    trees: [
        {
            name: 'Warcries',
            isActive: true,
            skills: [
                {
                    id: 1,
                    isPlaceholder: false,
                    name: 'Howl',
                    description: 'Frightens monsters into retreating. ',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: false,
                    name: 'Find Potion',
                    description: 'Grants a chance that a Health, Mana or Rejuvenation potion can be derived from a corpse. ',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: false,
                    name: 'Taunt',
                    description: 'Taunts a monster to walk to you and engage in melee range combat with you. Useful against spell casters and archer types. ',
                    points: 0,
                    prerequisites: ['Howl'],
                    unlockedBy: ['Howl'],
                    available: false,
                },
                {
                    id: 5,
                    isPlaceholder: false,
                    name: 'Shout',
                    description: 'Increases the defense of friendly units.',
                    points: 0,
                    prerequisites: ['Howl'],
                    unlockedBy: ['Howl'],
                    available: false,
                },
                {
                    id: 6,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 8,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 9,
                    isPlaceholder: false,
                    name: 'Find Item',
                    description: 'Grants a chance that an item can be found on a corpse.',
                    points: 0,
                    prerequisites: ['Find Potion'],
                    unlockedBy: ['Find Potion'],
                    available: false,
                },
                {
                    id: 10,
                    isPlaceholder: false,
                    name: 'Battle Cry',
                    description: 'Frightens nearby enemies, lowers their defense, and damage. ',
                    points: 0,
                    prerequisites: ['Howl','Taunt'],
                    unlockedBy: ['Taunt'],
                    available: false,
                },
                {
                    id: 11,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 14,
                    isPlaceholder: false,
                    name: 'Battle Orders',
                    description: 'Increases Mana, Life, and Stamina of party members.',
                    points: 0,
                    prerequisites: ['Howl', 'Shout'],
                    unlockedBy: ['Shout'],
                    available: false,
                },
                {
                    id: 15,
                    isPlaceholder: false,
                    name: 'Grim Ward',
                    description: 'Turns a corpse into a fetish that will frighten monsters away.',
                    points: 0,
                    prerequisites: ['Find Potion', 'Find Item'],
                    unlockedBy: ['Find Item'],
                    available: false,
                },
                {
                    id: 16,
                    isPlaceholder: false,
                    name: 'Warcry',
                    description: 'Damages and stuns your enemies. ',
                    points: 0,
                    prerequisites: ['Howl', 'Taunt', 'Shout', 'Battle Cry', 'Battle Orders'],
                    unlockedBy: ['Battle Cry', 'Battle Orders'],
                    available: false,
                },
                {
                    id: 17,
                    isPlaceholder: false,
                    name: 'Battle Command',
                    description: 'Temporarily increases the skills of party members by 1. ',
                    points: 0,
                    prerequisites: ['Howl', 'Shout', 'Battle Orders'],
                    unlockedBy: ['Battle Orders'],
                    available: false,
                },
                {
                    id: 18,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
        {
            name: 'Combat Masteries',
            isActive: false,
            skills: [
                {
                    id: 1,
                    isPlaceholder: false,
                    name: 'Sword Mastery',
                    description: 'Increased damage and Attack Rating when using swords.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: false,
                    name: 'Axe Mastery',
                    description: 'Increased damage and Attack Rating when using axes.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: false,
                    name: 'Mace Mastery',
                    description: 'Increased damage and Attack Rating when using maces.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: false,
                    name: 'Polearm Mastery',
                    description: 'Increased damage and Attack Rating when using polearms.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: false,
                    name: 'Throwing Mastery',
                    description: 'Increased damage and Attack Rating when throwing a weapon.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: false,
                    name: 'Spear Mastery',
                    description: 'Increased damage and Attack Rating when using spears.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: false,
                    name: 'Increased Stamina',
                    description: 'Increases stamina, and stamina recovery rate.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 8,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 9,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 10,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 11,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 12,
                    isPlaceholder: false,
                    name: 'Iron Skin',
                    description: 'Improves overall defense.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: true,
                    name: 'Increased Speed',
                    description: 'Increases your walk and run speeds.',
                    points: 0,
                    prerequisites: ['Increased Stamina'],
                    unlockedBy: ['Increased Stamina'],
                    available: false,
                },
                {
                    id: 14,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 15,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 16,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 17,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 18,
                    isPlaceholder: false,
                    name: 'Natural Resistance',
                    description: 'Increases resistances to elemental damage.',
                    points: 0,
                    prerequisites: ['Iron Skin'],
                    unlockedBy: ['Iron Skin'],
                    available: false,
                },
            ]
        },
        {
            name: 'Combat Skills',
            isActive: false,
            skills: [
                {
                    id: 1,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: false,
                    name: 'Bash',
                    description: 'A powerful smashing blow that knocks the target back.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: false,
                    name: 'Leap',
                    description: 'Barbarian jumps and knocks back enemies where he lands.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: false,
                    name: 'Double Swing',
                    description: 'A quick double attack that can damage two nearby enemies.',
                    points: 0,
                    prerequisites: ['Bash'],
                    unlockedBy: ['Bash'],
                    available: false,
                },
                {
                    id: 7,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 8,
                    isPlaceholder: false,
                    name: 'Stun',
                    description: 'A successful attack briefly stuns the enemy.',
                    points: 0,
                    prerequisites: ['Bash'],
                    unlockedBy: ['Bash'],
                    available: false,
                },
                {
                    id: 9,
                    isPlaceholder: false,
                    name: 'Double Throw',
                    description: 'Throws two weapons.',
                    points: 0,
                    prerequisites: ['Bash', 'Double Swing'],
                    unlockedBy: ['Double Swing'],
                    available: false,
                },
                {
                    id: 10,
                    isPlaceholder: false,
                    name: 'Leap Attack',
                    description: 'Leaps onto a target and attacks when landing.',
                    points: 0,
                    prerequisites: ['Leap'],
                    unlockedBy: ['Leap'],
                    available: false,
                },
                {
                    id: 11,
                    isPlaceholder: false,
                    name: 'Concentrate',
                    description: 'An uninterruptible attack that also temporarily improves your defense.',
                    points: 0,
                    prerequisites: ['Bash', 'Stun'],
                    unlockedBy: ['Stun'],
                    available: false,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 14,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 15,
                    isPlaceholder: false,
                    name: 'Frenzy',
                    description: 'Every successful hit increases your velocity and attack speed.',
                    points: 0,
                    prerequisites: ['Bash', 'Double Swing', 'Double Throw'],
                    unlockedBy: ['Double Throw'],
                    available: false,
                },
                {
                    id: 16,
                    isPlaceholder: false,
                    name: 'Whirlwind',
                    description: 'A fierce spinning attack.',
                    points: 0,
                    prerequisites: ['Bash', 'Leap', 'Stun', 'Concentrate', 'Leap Attack'],
                    unlockedBy: ['Concentrate', 'Leap Attack'],
                    available: false,
                },
                {
                    id: 17,
                    isPlaceholder: false,
                    name: 'Berserk',
                    description: 'A powerful attack that leaves the Barbarian more vulnerable.',
                    points: 0,
                    prerequisites: ['Bash', 'Stun', 'Concentrate'],
                    unlockedBy: ['Concentrate'],
                    available: false,
                },
                {
                    id: 18,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
    ],
}