export default {
    class: 'Druid',
    trees: [
        {
            name: 'Elemental',
            isActive: true,
            skills: [
                {
                    id: 1,
                    isPlaceholder: false,
                    name: 'Firestorm',
                    description: 'Wielding this ability, the Druid projects waves of molten earth that spread outward and burn a wide swath of destruction through his foes.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: false,
                    name: 'Molten Boulder',
                    description: 'By virtue of this talent, a Druid can summon forth a huge, rolling mass of magma, bowling over smaller enemies in its path before bursting into fiery shards.',
                    points: 0,
                    prerequisites: ['Firestorm'],
                    unlockedBy: ['Firestorm'],
                    available: false,
                },
                {
                    id: 5,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: false,
                    name: 'Arctic Blast',
                    description: 'Aided by the will of the North Winds, the Druid conjures up a chilling torrent of frost that incapacitates all caught within the frozen blast.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: false,
                    name: 'Fissure',
                    description: 'Sending his plea to the very core of the earth, the Druid rends the earth\'s very crust, tearing open volcanic vents beneath the feet of his adversaries, charring them to the bone.',
                    points: 0,
                    prerequisites: ['Firestorm', 'Molten Boulder'],
                    unlockedBy: ['Molten Boulder'],
                    available: false,
                },
                {
                    id: 8,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 9,
                    isPlaceholder: false,
                    name: 'Cyclone Armor',
                    description: 'This skill allows the Druid to sheath himself in a swirling mass of charged particles that absorbs damage from fire-, cold-, and lightning-based attacks.',
                    points: 0,
                    prerequisites: ['Arctic Blast'],
                    unlockedBy: ['Arctic Blast'],
                    available: false,
                },
                {
                    id: 10,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 11,
                    isPlaceholder: false,
                    name: 'Twister',
                    description: 'Calling to the winds, the Druid sends small whirlwinds advancing into the midst of his enemies, buffeting and stunning them as they go.',
                    points: 0,
                    prerequisites: ['Arctic Blast', 'Cyclone Armor'],
                    unlockedBy: ['Cyclone Armor'],
                    available: false,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: false,
                    name: 'Volcano',
                    description: 'A Druid trained in this ability possesses the power to summon from the bowels of the earth a violent eruption, raining molten rock down upon all nearby foes.',
                    points: 0,
                    prerequisites: ['Firestorm', 'Molten Boulder', 'Fissure'],
                    unlockedBy: ['Fissure'],
                    available: false,
                },
                {
                    id: 14,
                    isPlaceholder: false,
                    name: 'Tornado',
                    description: 'Manipulating the great winds into a fearsome cyclone, the Druid sends this force of destruction into a throng of opponents, crushing into them and leaving devastation in its wake.',
                    points: 0,
                    prerequisites: ['Arctic Blast', 'Cyclone Armor', 'Twister'],
                    unlockedBy: ['Twister'],
                    available: false,
                },
                {
                    id: 15,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 16,
                    isPlaceholder: false,
                    name: 'Armageddon',
                    description: 'This terrible force of nature\'s vengeance rains down flaming stones around the Druid who cast it, pummeling any opponents foolish enough to be caught in its fury.',
                    points: 0,
                    prerequisites: ['Firestorm', 'Molten Boulder', 'Arctic Blast', 'Fissure', 'Cyclone Armor', 'Twister', 'Tornado', 'Volcano', 'Hurricane'],
                    unlockedBy: ['Volcano', 'Hurricane'],
                    available: false,
                },
                {
                    id: 17,
                    isPlaceholder: false,
                    name: 'Hurricane',
                    description: 'Particularly talented Druids can summon this most potent gale of devastation. A fierce storm wreaks havoc around him, while the Druid stays cradled within the gentle calm of its eye.',
                    points: 0,
                    prerequisites: ['Arctic Blast', 'Cyclone Armor', 'Twister', 'Tornado'],
                    unlockedBy: ['Tornado'],
                    available: false,
                },
                {
                    id: 18,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
        {
            name: 'Shapeshifting',
            isActive: false,
            skills: [
                {
                    id: 1,
                    isPlaceholder: false,
                    name: 'Werewolf',
                    description: 'This ability allows an enlightened Druid to take on the form of a wolf, imparting to him quicker reflexes and heightened combat facilities.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: false,
                    name: 'Lycanthropy',
                    description: 'Passive Effect: Changing shape is quite a taxing ordeal for a Druid, and he can only assume animal forms for a limited time. This skill enhances his constitution while in animal form, thereby increasing the amount of time he can remain transformed.',
                    points: 0,
                    prerequisites: ['Werewolf'],
                    unlockedBy: ['Werewolf'],
                    available: false,
                },
                {
                    id: 3,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: false,
                    name: 'Werebear',
                    description: 'This skill empowers the Druid with the capacity to assume the form of a savage bear, granting him great strength and fortitude.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: false,
                    name: 'Feral Rage',
                    description: 'When in wolf form, the Druid using this ability enters a frenzied rage, viciously tearing into foes and becoming heartier with each consecutive attack.',
                    points: 0,
                    prerequisites: ['Werewolf'],
                    unlockedBy: ['Werewolf'],
                    available: false,
                },
                {
                    id: 8,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 9,
                    isPlaceholder: false,
                    name: 'Maul',
                    description: 'A Druid in Werebear form uses his mighty paws to rend brutal gashes in the flesh of his enemies. Using this ability, the fury of his assault increases with every opponent he kills.',
                    points: 0,
                    prerequisites: ['Werebear'],
                    unlockedBy: ['Werebear'],
                    available: false,
                },
                {
                    id: 10,
                    isPlaceholder: false,
                    name: 'Rabies',
                    description: 'When a Druid utilizes this ability, he toxifies his own saliva and attacks his enemies with a vicious bite, spreading a contagious disease that wracks the flesh of his infected opponents.',
                    points: 0,
                    prerequisites: ['Werewolf', 'Feral Rage'],
                    unlockedBy: ['Feral Rage'],
                    available: false,
                },
                {
                    id: 11,
                    isPlaceholder: false,
                    name: 'Fire Claws',
                    description: 'While in his animal form, a Druid can use his affinity with the natural elements in order to supplement his attacks with a blazing assault.',
                    points: 0,
                    prerequisites: ['Werewolf', 'Werebear', 'Feral Rage', 'Maul'],
                    unlockedBy: ['Feral Rage', 'Maul'],
                    available: false,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 14,
                    isPlaceholder: false,
                    name: 'Hunger',
                    description: 'Nature gives life, but it can also snatch it back. When a Druid using this ability bites an opponent, he drains some of his victim\'s vital essence, replenishing his own.',
                    points: 0,
                    prerequisites: ['Werewolf', 'Werebear', 'Feral Rage', 'Maul', 'Fire Claws'],
                    unlockedBy: ['Fire Claws'],
                    available: false,
                },
                {
                    id: 15,
                    isPlaceholder: false,
                    name: 'Shock Wave',
                    description: 'With a tremendous roar, the Druid shakes the earth, stunning any enemies in the surrounding area with the resultant tremor.',
                    points: 0,
                    prerequisites: ['Werebear', 'Maul'],
                    unlockedBy: ['Maul'],
                    available: false,
                },
                {
                    id: 16,
                    isPlaceholder: false,
                    name: 'Fury',
                    description: 'The use of this skill drives the Druid into a bloodthirsty frenzy, attacking many foes with a raging fervor.',
                    points: 0,
                    prerequisites: ['Werewolf', 'Feral Rage', 'Rabies'],
                    unlockedBy: ['Rabies'],
                    available: false,
                },
                {
                    id: 17,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 18,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
        {
            name: 'Summoning',
            isActive: false,
            skills: [
                {
                    id: 1,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: false,
                    name: 'Raven',
                    description: 'Summon Ravens to peck out the eyes of your enemies. Ravens will cast "blind" on enemies they attack.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: false,
                    name: 'Poison Creeper',
                    description: 'A more subtle ally, these intelligent vines travel through the ground and use their cruel thorns to poison any opponents they contact.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: false,
                    name: 'Oak Sage',
                    description: 'The Druid uses this ability to call upon a helpful spirit of Nature to enhance his well-being, as well as the health of his companions.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: false,
                    name: 'Summon Spirit Wolf',
                    description: 'This gift of Nature allows the Druid to conjure forth one or more wolf allies who, with their mystical powers, provide the Druid a potent and ferocious colleague.',
                    points: 0,
                    prerequisites: ['Raven'],
                    unlockedBy: ['Raven'],
                    available: false,
                },
                {
                    id: 6,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 8,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 9,
                    isPlaceholder: false,
                    name: 'Carrion Vine',
                    description: 'The sentient plant summoned by this skill draws the corpses of your enemies into the ground, where it rapidly decomposes them, giving their life energies to the Druid who summoned it.',
                    points: 0,
                    prerequisites: ['Poison Creeper'],
                    unlockedBy: ['Poison Creeper'],
                    available: false,
                },
                {
                    id: 10,
                    isPlaceholder: false,
                    name: 'Heart of Wolverine',
                    description: 'This ability grants the Druid the knowledge needed to summon into being a spirit that increases his skill in battle, as well as that of his party.',
                    points: 0,
                    prerequisites: ['Oak Sage'],
                    unlockedBy: ['Oak Sage'],
                    available: false,
                },
                {
                    id: 11,
                    isPlaceholder: false,
                    name: 'Summon Dire Wolf',
                    description: 'This blessing from Nature imparts to the Druid the ability to summon several great wolves. Though the wolf is already fierce in combat, its savagery becomes greatly inflamed as it consumes the corpses of fallen foes.',
                    points: 0,
                    prerequisites: ['Raven', 'Oak Sage', 'Summon Spirit Wolf'],
                    unlockedBy: ['Oak Sage', 'Summon Spirit Wolf'],
                    available: false,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 14,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 15,
                    isPlaceholder: false,
                    name: 'Solar Creeper',
                    description: 'This skill conjures forth an intelligent plant that draws the enemy\'s dead deep into the earth, where it drains their spiritual essences and bestows them upon the Druid who summoned it.',
                    points: 0,
                    prerequisites: ['Poison Creeper', 'Carrion Vine'],
                    unlockedBy: ['Carrion Vine'],
                    available: false,
                },
                {
                    id: 16,
                    isPlaceholder: false,
                    name: 'Spirit of Barbs',
                    description: 'The spirit invoked by this skill bestows upon the Druid and his company the mystical ability to reflect damage back at any opponents who injure them.',
                    points: 0,
                    prerequisites: ['Oak Sage', 'Heart of Wolverine'],
                    unlockedBy: ['Heart of Wolverine'],
                    available: false,
                },
                {
                    id: 17,
                    isPlaceholder: false,
                    name: 'Summon Grizzly',
                    description: 'This boon grants the Druid the aid of a tremendous wild bear with huge claws and great fangs that fights ferociously alongside him with terrible strength and unmatched fury.',
                    points: 0,
                    prerequisites: ['Raven', 'Oak Sage', 'Summon Spirit Wolf', 'Summon Dire Wolf'],
                    unlockedBy: ['Summon Dire Wolf'],
                    available: false,
                },
                {
                    id: 18,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
    ],
}