export default {
    class: 'Paladin',
    trees: [
        {
            name: 'Defensive Auras',
            isActive: true,
            skills: [
                {
                    id: 1,
                    isPlaceholder: false,
                    name: 'Prayer',
                    description: 'Heals all party members.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: false,
                    name: 'Resist Fire',
                    description: 'Increases the Fire resistance of all party members. ',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: false,
                    name: 'Defiance',
                    description: 'Boosts the Defense of all party members.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: false,
                    name: 'Resist Cold',
                    description: 'Increases the Cold resistance of all party members. ',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: false,
                    name: 'Cleansing',
                    description: 'Reduces Poison and Curse duration for all party members.',
                    points: 0,
                    prerequisites: ['Prayer'],
                    unlockedBy: ['Prayer'],
                    available: false,
                },
                {
                    id: 8,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 9,
                    isPlaceholder: false,
                    name: 'Resist Lightning',
                    description: 'Increases the Lighting resistance of all party members.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 10,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 11,
                    isPlaceholder: false,
                    name: 'Vigor',
                    description: 'Increases Speed, Stamina, and Stamina recovery for all party members.',
                    points: 0,
                    prerequisites: ['Prayer', 'Cleansing', 'Defiance'],
                    unlockedBy: ['Cleansing', 'Defiance'],
                    available: false,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: false,
                    name: 'Meditation',
                    description: 'Boosts Mana recovery for all party members.',
                    points: 0,
                    prerequisites: ['Prayer', 'Cleansing'],
                    unlockedBy: ['Cleansing'],
                    available: false,
                },
                {
                    id: 14,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 15,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 16,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 17,
                    isPlaceholder: false,
                    name: 'Redemption',
                    description: 'Periodically attempts to redeem corpses for Health and Mana.',
                    points: 0,
                    prerequisites: ['Prayer', 'Cleansing', 'Defiance', 'Vigor'],
                    unlockedBy: ['Vigor'],
                    available: false,
                },
                {
                    id: 18,
                    isPlaceholder: false,
                    name: 'Salvation',
                    description: 'Increases all Elemental resistances for all party members.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
        {
            name: 'Offensive Auras',
            isActive: false,
            skills: [
                {
                    id: 1,
                    isPlaceholder: false,
                    name: 'Might',
                    description: 'Increases damage dealt by party members.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: false,
                    name: 'Holy Fire',
                    description: 'Periodically does Fire damage to nearby enemies.',
                    points: 0,
                    prerequisites: ['Might'],
                    unlockedBy: ['Might'],
                    available: false,
                },
                {
                    id: 6,
                    isPlaceholder: false,
                    name: 'Thorns',
                    description: 'Enemies take damage when they cause melee damage to party members.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: false,
                    name: 'Blessed Aim',
                    description: 'Increases Attack Rating.',
                    points: 0,
                    prerequisites: ['Might'],
                    unlockedBy: ['Might'],
                    available: false,
                },
                {
                    id: 8,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 9,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 10,
                    isPlaceholder: false,
                    name: 'Concentration',
                    description: 'Reduces the chance that your attacks will be interrupted.',
                    points: 0,
                    prerequisites: ['Might', 'Blessed Aim'],
                    unlockedBy: ['Blessed Aim'],
                    available: false,
                },
                {
                    id: 11,
                    isPlaceholder: false,
                    name: 'Holy Freeze',
                    description: 'Periodically slows enemies nearby.',
                    points: 0,
                    prerequisites: ['Might', 'Holy Fire'],
                    unlockedBy: ['Holy Fire'],
                    available: false,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 14,
                    isPlaceholder: false,
                    name: 'Holy Shock',
                    description: 'Periodically does Lightning damage to enemies within a radius.',
                    points: 0,
                    prerequisites: ['Might', 'Holy Fire', 'Holy Freeze'],
                    unlockedBy: ['Holy Freeze'],
                    available: false,
                },
                {
                    id: 15,
                    isPlaceholder: false,
                    name: 'Sanctuary',
                    description: 'Damages and does knockback to the Undead. Ignores Physical Resistances and Immunities Of Undead Monsters.',
                    points: 0,
                    prerequisites: ['Might', 'Thorns', 'Holy Fire', 'Holy Freeze'],
                    unlockedBy: ['Thorns', 'Holy Freeze'],
                    available: false,
                },
                {
                    id: 16,
                    isPlaceholder: false,
                    name: 'Fanatiscism',
                    description: 'Increases your Attack Rate and Attack Rating. Increases damage for all party members.',
                    points: 0,
                    prerequisites: ['Might', 'Blessed Aim', 'Concentration'],
                    unlockedBy: ['Concentration'],
                    available: false,
                },
                {
                    id: 17,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 18,
                    isPlaceholder: false,
                    name: 'Conviction',
                    description: 'Reduces enemy Defense and the Resistances of monsters.',
                    points: 0,
                    prerequisites: ['Might', 'Thorns', 'Holy Fire', 'Holy Freeze', 'Sanctuary'],
                    unlockedBy: ['Sanctuary'],
                    available: false,
                },
            ]
        },
        {
            name: 'Combat Skills',
            isActive: false,
            skills: [
                {
                    id: 1,
                    isPlaceholder: false,
                    name: 'Sacrifice',
                    description: 'Increased damage at the cost of health.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 2,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 3,
                    isPlaceholder: false,
                    name: 'Smite',
                    description: 'Shield bash that does damage and knock back.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 4,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 5,
                    isPlaceholder: false,
                    name: 'Holy Bolt',
                    description: 'Bolt of energy that damages undead, or heals friendly units.',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 6,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 7,
                    isPlaceholder: false,
                    name: 'Zeal',
                    description: 'Quickly attacks multiple adjacent enemies.',
                    points: 0,
                    prerequisites: ['Sacrifice'],
                    unlockedBy: ['Sacrifice'],
                    available: false,
                },
                {
                    id: 8,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 9,
                    isPlaceholder: false,
                    name: 'Charge',
                    description: 'Closes the distance with an enemy, delivering a bash on contact.',
                    points: 0,
                    prerequisites: ['Smite'],
                    unlockedBy: ['Smite'],
                    available: false,
                },
                {
                    id: 10,
                    isPlaceholder: false,
                    name: 'Vengeance',
                    description: 'Adds Elemental (Fire, Lightning and Cold) damage to all melee attacks.',
                    points: 0,
                    prerequisites: ['Sacrifice', 'Zeal'],
                    unlockedBy: ['Zeal'],
                    available: false,
                },
                {
                    id: 11,
                    isPlaceholder: false,
                    name: 'Blessed Hammer',
                    description: 'A summoned Hammer spirals outward, damaging enemies. The Undead take additional damage.',
                    points: 0,
                    prerequisites: ['Holy Bolt'],
                    unlockedBy: ['Holy Bolt'],
                    available: false,
                },
                {
                    id: 12,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 13,
                    isPlaceholder: false,
                    name: 'Conversion',
                    description: 'A successful attack has a chance to convert the target to fight evil.',
                    points: 0,
                    prerequisites: ['Sacrifice', 'Zeal', 'Vengeance'],
                    unlockedBy: ['Vengeance'],
                    available: false,
                },
                {
                    id: 14,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 15,
                    isPlaceholder: false,
                    name: 'Holy Shield',
                    description: 'Magically enhances shield to give defense bonuses.',
                    points: 0,
                    prerequisites: ['Smite', 'Holy Bolt', 'Charge', 'Blessed Hammer'],
                    unlockedBy: ['Charge', 'Blessed Hammer'],
                    available: false,
                },
                {
                    id: 16,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
                {
                    id: 17,
                    isPlaceholder: false,
                    name: 'Fist of the Heavens',
                    description: 'Lightning attack from the sky that releases Holy Bolts.',
                    points: 0,
                    prerequisites: ['Sacrifice', 'Holy Bolt', 'Zeal', 'Vengeance', 'Blessed Hammer', 'Conversion'],
                    unlockedBy: ['Blessed Hammer', 'Conversion'],
                    available: false,
                },
                {
                    id: 18,
                    isPlaceholder: true,
                    name: 'Placeholder',
                    description: 'Placeholder',
                    points: 0,
                    prerequisites: ['None'],
                    unlockedBy: ['None'],
                    available: true,
                },
            ]
        },
    ],
}